#include "DxLib.h"
#include "ImageHandles.h"


int ImageHandles::FULLBODY_ICHIGOCHAN_NORMAL;
int ImageHandles::FULLBODY_ICHIGOCHAN_AVATAR;
int ImageHandles::FULLBODY_MOFU;
int ImageHandles::FULLBODY_NEON;
int ImageHandles::FULLBODY_TOROI;

int ImageHandles::SPRITE_ICHIGOCHAN;
int ImageHandles::SPRITE_MOFU;
int ImageHandles::SPRITE_NEON;
int ImageHandles::SPRITE_TOROI;
int ImageHandles::SPRITE_ZKCHR_KURAGE;
int ImageHandles::SPRITE_ZKCHR_KUJIRA;
int ImageHandles::SPRITE_ZKCHR_LIGHT_ELE;
int ImageHandles::SPRITE_ZKCHR_KNIGHT_RAY;
int ImageHandles::SPRITE_ZKCHR_GOZGOK;
int ImageHandles::SPRITE_ZKCHR_MEZDOROGON;

int ImageHandles::ANCHOR_BLACK;
int ImageHandles::ANCHOR_GRAY;
int ImageHandles::ANCHOR_SILVER;
int ImageHandles::ANCHOR_WHITE;
int ImageHandles::ANCHOR_BLUE;
int ImageHandles::ANCHOR_NAVY;
int ImageHandles::ANCHOR_TEAL;
int ImageHandles::ANCHOR_GREEN;
int ImageHandles::ANCHOR_LIME;
int ImageHandles::ANCHOR_AQUA;
int ImageHandles::ANCHOR_YELLOW;
int ImageHandles::ANCHOR_RED;
int ImageHandles::ANCHOR_FUCHSIA;
int ImageHandles::ANCHOR_OLIVE;
int ImageHandles::ANCHOR_PURPLE;
int ImageHandles::ANCHOR_MAROON;

int ImageHandles::BUBBLE_BLACK;
int ImageHandles::BUBBLE_GRAY;
int ImageHandles::BUBBLE_SILVER;
int ImageHandles::BUBBLE_WHITE;
int ImageHandles::BUBBLE_BLUE;
int ImageHandles::BUBBLE_NAVY;
int ImageHandles::BUBBLE_TEAL;
int ImageHandles::BUBBLE_GREEN;
int ImageHandles::BUBBLE_LIME;
int ImageHandles::BUBBLE_AQUA;
int ImageHandles::BUBBLE_YELLOW;
int ImageHandles::BUBBLE_RED;
int ImageHandles::BUBBLE_FUCHSIA;
int ImageHandles::BUBBLE_OLIVE;
int ImageHandles::BUBBLE_PURPLE;
int ImageHandles::BUBBLE_MAROON;

int ImageHandles::CRYSTAL_BLACK;
int ImageHandles::CRYSTAL_GRAY;
int ImageHandles::CRYSTAL_SILVER;
int ImageHandles::CRYSTAL_WHITE;
int ImageHandles::CRYSTAL_BLUE;
int ImageHandles::CRYSTAL_NAVY;
int ImageHandles::CRYSTAL_TEAL;
int ImageHandles::CRYSTAL_GREEN;
int ImageHandles::CRYSTAL_LIME;
int ImageHandles::CRYSTAL_AQUA;
int ImageHandles::CRYSTAL_YELLOW;
int ImageHandles::CRYSTAL_RED;
int ImageHandles::CRYSTAL_FUCHSIA;
int ImageHandles::CRYSTAL_OLIVE;
int ImageHandles::CRYSTAL_PURPLE;
int ImageHandles::CRYSTAL_MAROON;

int ImageHandles::STRAWBERRY_BLACK;
int ImageHandles::STRAWBERRY_GRAY;
int ImageHandles::STRAWBERRY_SILVER;
int ImageHandles::STRAWBERRY_WHITE;
int ImageHandles::STRAWBERRY_BLUE;
int ImageHandles::STRAWBERRY_NAVY;
int ImageHandles::STRAWBERRY_TEAL;
int ImageHandles::STRAWBERRY_GREEN;
int ImageHandles::STRAWBERRY_LIME;
int ImageHandles::STRAWBERRY_AQUA;
int ImageHandles::STRAWBERRY_YELLOW;
int ImageHandles::STRAWBERRY_RED;
int ImageHandles::STRAWBERRY_FUCHSIA;
int ImageHandles::STRAWBERRY_OLIVE;
int ImageHandles::STRAWBERRY_PURPLE;
int ImageHandles::STRAWBERRY_MAROON;

int ImageHandles::POTATO_BASIC;
int ImageHandles::POTATO_BLACK;
int ImageHandles::POTATO_GRAY;
int ImageHandles::POTATO_SILVER;
int ImageHandles::POTATO_WHITE;
int ImageHandles::POTATO_BLUE;
int ImageHandles::POTATO_NAVY;
int ImageHandles::POTATO_TEAL;
int ImageHandles::POTATO_GREEN;
int ImageHandles::POTATO_LIME;
int ImageHandles::POTATO_AQUA;
int ImageHandles::POTATO_YELLOW;
int ImageHandles::POTATO_RED;
int ImageHandles::POTATO_FUCHSIA;
int ImageHandles::POTATO_OLIVE;
int ImageHandles::POTATO_PURPLE;
int ImageHandles::POTATO_MAROON;

int ImageHandles::GHOST_RED_FRONT;
int ImageHandles::GHOST_RED_BACK;
int ImageHandles::GHOST_ORANGE_FRONT;
int ImageHandles::GHOST_ORANGE_BACK;
int ImageHandles::GHOST_YELLOW_FRONT;
int ImageHandles::GHOST_YELLOW_BACK;
int ImageHandles::GHOST_GREEN_FRONT;
int ImageHandles::GHOST_GREEN_BACK;
int ImageHandles::GHOST_TEAL_FRONT;
int ImageHandles::GHOST_TEAL_BACK;
int ImageHandles::GHOST_AQUA_FRONT;
int ImageHandles::GHOST_AQUA_BACK;
int ImageHandles::GHOST_BLUE_FRONT;
int ImageHandles::GHOST_BLUE_BACK;
int ImageHandles::GHOST_PURPLE_FRONT;
int ImageHandles::GHOST_PURPLE_BACK;
int ImageHandles::GHOST_FUCHSIA_FRONT;
int ImageHandles::GHOST_FUCHSIA_BACK;
int ImageHandles::GHOST_SILVER_FRONT;
int ImageHandles::GHOST_SILVER_BACK;
int ImageHandles::GHOST_GRAY_FRONT;
int ImageHandles::GHOST_GRAY_BACK;

int ImageHandles::LAIDENJAR0;
int ImageHandles::LAIDENJAR1;
int ImageHandles::LAIDENJAR2;
int ImageHandles::LAIDENJAR3;

int ImageHandles::RASER_RED;
int ImageHandles::RASER_ORANGE;
int ImageHandles::RASER_YELLOW;
int ImageHandles::RASER_GREEN;
int ImageHandles::RASER_TEAL;
int ImageHandles::RASER_AQUA;
int ImageHandles::RASER_BLUE;
int ImageHandles::RASER_PURPLE;
int ImageHandles::RASER_FUCHSIA;
int ImageHandles::RASER_SILVER;
int ImageHandles::RASER_GRAY;

int ImageHandles::LOGO;
int ImageHandles::LOGO_NONSILHOUETTE;
int ImageHandles::ICHIGOCHAN_CONCEPTUAL;
int ImageHandles::SCREEN_BACKGROUND;
int ImageHandles::SCREEN_BACKGROUND_CROPPED;
int ImageHandles::FIELD_BACKGROUND_STAGE1;
int ImageHandles::DIGIT_CURSOR;
int ImageHandles::NARRATIVE_POP;

int ImageHandles::FIELD_BACKGROUND;
int ImageHandles::TEST_SHOOTER;
int ImageHandles::BLUE_MARBLE;
int ImageHandles::RED_MARBLE;
int ImageHandles::ORANGE_TRIANGLE;
int ImageHandles::MAJIKICHI_SMILE;
int ImageHandles::HAND_POWER;
int ImageHandles::PIEN;
int ImageHandles::HEART;
int ImageHandles::MELTING_FACE;
int ImageHandles::THINKING_FACE;
int ImageHandles::SUNGLASS_FACE;
int ImageHandles::KURAGE;
int ImageHandles::KUJIRA;


void ImageHandles::LOAD_ALL_IMAGE() {
	FULLBODY_ICHIGOCHAN_NORMAL = DxLib::LoadGraph("image/stand/1.png");
	FULLBODY_ICHIGOCHAN_AVATAR = DxLib::LoadGraph("image/stand/2.png");
	FULLBODY_MOFU = DxLib::LoadGraph("image/stand/3.png");
	FULLBODY_NEON = DxLib::LoadGraph("image/stand/4.png");
	FULLBODY_TOROI = DxLib::LoadGraph("image/stand/5.png");

	SPRITE_ICHIGOCHAN = DxLib::LoadGraph("image/sprite/character/6.png");
	SPRITE_MOFU = DxLib::LoadGraph("image/sprite/character/7.png");
	SPRITE_NEON = DxLib::LoadGraph("image/sprite/character/8.png");
	SPRITE_TOROI = DxLib::LoadGraph("image/sprite/character/9.png");
	SPRITE_ZKCHR_KURAGE = DxLib::LoadGraph("image/sprite/character/10.png");
	SPRITE_ZKCHR_KUJIRA = DxLib::LoadGraph("image/sprite/character/11.png");
	SPRITE_ZKCHR_LIGHT_ELE = DxLib::LoadGraph("image/sprite/character/14.png");
	SPRITE_ZKCHR_KNIGHT_RAY = DxLib::LoadGraph("image/sprite/character/15.png");
	SPRITE_ZKCHR_GOZGOK = DxLib::LoadGraph("image/sprite/character/12.png");
	SPRITE_ZKCHR_MEZDOROGON = DxLib::LoadGraph("image/sprite/character/13.png");

	ANCHOR_BLACK = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor01black.png");
	ANCHOR_GRAY = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor02gray.png");
	ANCHOR_SILVER = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor03silver.png");
	ANCHOR_WHITE = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor04white.png");
	ANCHOR_BLUE = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor05blue.png");
	ANCHOR_NAVY = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor06navy.png");
	ANCHOR_TEAL = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor07teal.png");
	ANCHOR_GREEN = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor08green.png");
	ANCHOR_LIME = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor09lime.png");
	ANCHOR_AQUA = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor10aqua.png");
	ANCHOR_YELLOW = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor11yellow.png");
	ANCHOR_RED = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor12red.png");
	ANCHOR_FUCHSIA = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor13fuchsia.png");
	ANCHOR_OLIVE = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor14olive.png");
	ANCHOR_PURPLE = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor15purple.png");
	ANCHOR_MAROON = DxLib::LoadGraph("image/sprite/bullet/Anchor/Anchor16maroon.png");

	BUBBLE_BLACK = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble01black.png");
	BUBBLE_GRAY = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble02gray.png");
	BUBBLE_SILVER = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble03silver.png");
	BUBBLE_WHITE = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble04white.png");
	BUBBLE_BLUE = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble05blue.png");
	BUBBLE_NAVY = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble06navy.png");
	BUBBLE_TEAL = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble07teal.png");
	BUBBLE_GREEN = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble08green.png");
	BUBBLE_LIME = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble09lime.png");
	BUBBLE_AQUA = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble10aqua.png");
	BUBBLE_YELLOW = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble11yellow.png");
	BUBBLE_RED = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble12red.png");
	BUBBLE_FUCHSIA = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble13fuchsia.png");
	BUBBLE_OLIVE = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble14olive.png");
	BUBBLE_PURPLE = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble15purple.png");
	BUBBLE_MAROON = DxLib::LoadGraph("image/sprite/bullet/Bubble/Bubble16maroon.png");

	CRYSTAL_BLACK = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal01black.png");
	CRYSTAL_GRAY = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal02gray.png");
	CRYSTAL_SILVER = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal03silver.png");
	CRYSTAL_WHITE = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal04white.png");
	CRYSTAL_BLUE = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal05blue.png");
	CRYSTAL_NAVY = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal06navy.png");
	CRYSTAL_TEAL = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal07teal.png");
	CRYSTAL_GREEN = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal08green.png");
	CRYSTAL_LIME = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal09lime.png");
	CRYSTAL_AQUA = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal10aqua.png");
	CRYSTAL_YELLOW = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal11yellow.png");
	CRYSTAL_RED = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal12red.png");
	CRYSTAL_FUCHSIA = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal13fuchsia.png");
	CRYSTAL_OLIVE = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal14olive.png");
	CRYSTAL_PURPLE = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal15purple.png");
	CRYSTAL_MAROON = DxLib::LoadGraph("image/sprite/bullet/Crystal/Crystal16maroon.png");

	STRAWBERRY_BLACK = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry01black.png");
	STRAWBERRY_GRAY = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry02gray.png");
	STRAWBERRY_SILVER = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry03silver.png");
	STRAWBERRY_WHITE = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry04white.png");
	STRAWBERRY_BLUE = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry05blue.png");
	STRAWBERRY_NAVY = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry06navy.png");
	STRAWBERRY_TEAL = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry07teal.png");
	STRAWBERRY_GREEN = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry08green.png");
	STRAWBERRY_LIME = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry09lime.png");
	STRAWBERRY_AQUA = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry10aqua.png");
	STRAWBERRY_YELLOW = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry11yellow.png");
	STRAWBERRY_RED = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry12red.png");
	STRAWBERRY_FUCHSIA = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry13fuchsia.png");
	STRAWBERRY_OLIVE = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry14olive.png");
	STRAWBERRY_PURPLE = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry15purple.png");
	STRAWBERRY_MAROON = DxLib::LoadGraph("image/sprite/bullet/Strawberry/Strawberry16maroon.png");

	POTATO_BASIC = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato00basic.png");
	POTATO_BLACK = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato01black.png");
	POTATO_GRAY = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato02gray.png");
	POTATO_SILVER = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato03silver.png");
	POTATO_WHITE = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato04white.png");
	POTATO_BLUE = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato05blue.png");
	POTATO_NAVY = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato06navy.png");
	POTATO_TEAL = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato07teal.png");
	POTATO_GREEN = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato08green.png");
	POTATO_LIME = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato09lime.png");
	POTATO_AQUA = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato10aqua.png");
	POTATO_YELLOW = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato11yellow.png");
	POTATO_RED = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato12red.png");
	POTATO_FUCHSIA = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato13fuchsia.png");
	POTATO_OLIVE = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato14olive.png");
	POTATO_PURPLE = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato15purple.png");
	POTATO_MAROON = DxLib::LoadGraph("image/sprite/bullet/Potato/Potato16maroon.png");

	GHOST_RED_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01red1.png");
	GHOST_RED_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01red2.png");
	GHOST_ORANGE_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01orange1.png");
	GHOST_ORANGE_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01orange2.png");
	GHOST_YELLOW_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01yellow1.png");
	GHOST_YELLOW_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01yellow2.png");
	GHOST_GREEN_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01green1.png");
	GHOST_GREEN_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01green2.png");
	GHOST_TEAL_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01teal1.png");
	GHOST_TEAL_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01teal2.png");
	GHOST_AQUA_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01aqua1.png");
	GHOST_AQUA_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01aqua2.png");
	GHOST_BLUE_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01blue1.png");
	GHOST_BLUE_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01blue2.png");
	GHOST_PURPLE_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01purple1.png");
	GHOST_PURPLE_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01purple2.png");
	GHOST_FUCHSIA_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01fuchsia1.png");
	GHOST_FUCHSIA_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01fuchsia2.png");
	GHOST_SILVER_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01silver1.png");
	GHOST_SILVER_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01silver2.png");
	GHOST_GRAY_FRONT = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01gray1.png");
	GHOST_GRAY_BACK = DxLib::LoadGraph("image/sprite/object/Ghost/Ghost01gray2.png");

	LAIDENJAR0 = DxLib::LoadGraph("image/sprite/object/LaidenJar/LaidenJar0.png");
	LAIDENJAR1 = DxLib::LoadGraph("image/sprite/object/LaidenJar/LaidenJar1.png");
	LAIDENJAR2 = DxLib::LoadGraph("image/sprite/object/LaidenJar/LaidenJar2.png");
	LAIDENJAR3 = DxLib::LoadGraph("image/sprite/object/LaidenJar/LaidenJar3.png");

	RASER_RED = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser01red.png");
	RASER_ORANGE = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser02orange.png");
	RASER_YELLOW = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser03yellow.png");
	RASER_GREEN = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser04green.png");
	RASER_TEAL = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser05teal.png");
	RASER_AQUA = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser06aqua.png");
	RASER_BLUE = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser07blue.png");
	RASER_PURPLE = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser08purple.png");
	RASER_FUCHSIA = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser09fuchsia.png");
	RASER_SILVER = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser10silver.png");
	RASER_GRAY = DxLib::LoadGraph("image/sprite/bullet/Raser/Raser11gray.png");

	LOGO = DxLib::LoadGraph("image/DCSロゴ_シルエットあり.png");
	LOGO_NONSILHOUETTE = DxLib::LoadGraph("image/DCSロゴ.png");
	ICHIGOCHAN_CONCEPTUAL = DxLib::LoadGraph("image/いちごちゃん_タイトル画面.png");
	SCREEN_BACKGROUND = DxLib::LoadGraph("image/スクリーン背景.png");
	SCREEN_BACKGROUND_CROPPED = DxLib::LoadGraph("image/スクリーン背景_くりぬき.png");
	FIELD_BACKGROUND_STAGE1 = DxLib::LoadGraph("image/フィールド背景_ステージ1.png");
	DIGIT_CURSOR = DxLib::LoadGraph("image/DigitCursor.png");
	NARRATIVE_POP = DxLib::LoadGraph("image/会話テキストポップ.png");

	//FIELD_BACKGROUND = DxLib::LoadGraph("image/test/field.png");
	//TEST_SHOOTER = DxLib::LoadGraph("image/test/pink_triangle.png");
	//BLUE_MARBLE = DxLib::LoadGraph("image/test/blue_marble.png");
	//RED_MARBLE = DxLib::LoadGraph("image/test/red_marble.png");
	//ORANGE_TRIANGLE = DxLib::LoadGraph("image/test/orange_triangle.png");
	//MAJIKICHI_SMILE = DxLib::LoadGraph("image/test/majikichi_smile.png");
	//HAND_POWER = DxLib::LoadGraph("image/test/hand_power.png");
	//PIEN = DxLib::LoadGraph("image/test/pien.png");
	//HEART = DxLib::LoadGraph("image/test/heart.png");
	//MELTING_FACE = DxLib::LoadGraph("image/test/melting_face.png");
	//THINKING_FACE = DxLib::LoadGraph("image/test/thinking_face.png");
	//SUNGLASS_FACE = DxLib::LoadGraph("image/test/sun_glass_face.png");
	//KURAGE = DxLib::LoadGraph("image/test/kurage.png");
	//KUJIRA = DxLib::LoadGraph("image/test/kujira.png");
}